TestTask1/urls.py
from django.conf.urls.\
defaults import patterns, include, url
from django.views.generic import DetailView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
from main.models import Person
from main.views import RequestListView


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^requests/(?P<page>\d+)/$', RequestListView.as_view()),
    url(r'^requests/$', RequestListView.as_view()),

    url(r'^request/(?P<pk>\d+)/(?P<action>inc|dec)/$',
        'TestTask1.main.views.change_priority_view'),

    url(r'^$', DetailView.as_view(
        model=Person,
        template_name='main_page.html'), {'pk': 1}),

    url(r'^login/$', 'django.contrib.auth.views.login',
            {'template_name': 'login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
            {'next_page': '/', 'template_name': 'login.html'}),
    url(r'^edit/$', 'TestTask1.main.views.edit_person_view'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)
if settings.DEBUG:
# static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT}))

TestTask1/main/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.db import connection


class Request(models.Model):
    header = models.CharField(max_length=100)
    body = models.CharField(max_length=300)
    time = models.DateTimeField(auto_now_add=True)
    priority = models.IntegerField(default=0)

    def __unicode__(self):
        return 'Request at {0}: {1}'.format(self.time, self.header)

    class Meta:
        ordering = ["priority", "time"]


class Person(models.Model):
    name = models.CharField(max_length=25)
    surname = models.CharField(max_length=25)
    birth_date = models.DateField()
    bio = models.TextField(max_length=400)
    skype = models.CharField(max_length=20)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    photo = models.ImageField(upload_to='avatar', blank=True, null=True)


class SignalInfo(models.Model):
    datetime = models.DateTimeField(auto_now_add=True)
    header = models.CharField(max_length=256)
    model = models.CharField(max_length=256)
    app = models.CharField(max_length=256)
    action = models.CharField(max_length=256)
    object_pk = models.PositiveIntegerField()

    def get_instance(self):
        c = ContentType.objects.get(app_label=self.app, model=self.model)
        return c.get_object_for_this_type(pk=self.object_pk)

    def __unicode__(self):
        return '{0} at {1}'.format(self.header, self.datetime)


def _db_table_exists(table):
    cursor = connection.cursor()
    table_names = connection.introspection.get_table_list(cursor)
    return table in table_names


def initial_edit_callback(sender, created, instance, **kwargs):
    if (not _db_table_exists('main_signalinfo')):
        return
    post_save.disconnect(initial_edit_callback)
    post_save.connect(edit_callback)


def edit_callback(sender, created, instance, **kwargs):
    if sender == SignalInfo:
        return
    if kwargs.get('raw', True):
        return
    if created:
        action = 'created'
    else:
        action = 'edited'
    c = ContentType.objects.get_for_model(instance)
    s = SignalInfo(header='\'{0}\' was {1}'.format(instance, action),
        action=action, model=c.model, app=c.app_label, object_pk=c.pk)
    s.save()


def delete_callback(sender, instance, **kwargs):
    if (not sender == SignalInfo):
        action = 'deleted'
        c = ContentType.objects.get_for_model(instance)
        s = SignalInfo(header='\'{0}\' was {1}'.format(instance, action),
            action=action, model=c.model, app=c.app_label, object_pk=c.pk)
        s.save()


post_save.connect(initial_edit_callback)
pre_delete.connect(delete_callback)

TestTask1/main/forms.py
from TestTask1.main.widgets import JQueryDateWidget
from django.forms import ModelForm
from TestTask1.main.models import Person


class PersonForm(ModelForm):
    class Meta:
        model = Person

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget = JQueryDateWidget()

TestTask1/main/views.py
# Create your views here.
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.http import  HttpResponse
from django.shortcuts import render_to_response, redirect
from django.template.context import RequestContext
from django.utils import simplejson
from django.views.generic.list import ListView
from TestTask1.main.forms import PersonForm
from TestTask1.main.models import Person, Request


@login_required
def edit_person_view(request):
    p = Person.objects.all()[0]
    if request.method == 'POST':
        form = PersonForm(request.POST, request.FILES)
        if form.is_valid():
            np = form.save(commit=False)
            if (np.photo.name == None):
                np.photo = p.photo
            np.pk = 1
            np.save()
            try:
                if request.POST['isJS'] == 'no':
                    return redirect('/edit/')
            except:
                return HttpResponse(simplejson.dumps({'response': np.photo.url,
                                                      'result': 'success'}))
        else:
            response = {}
            for k in form.errors:
                response[k] = form.errors[k][0]
            try:
                if request.POST['isJS'] == 'no':
                    c = {'form': form, 'profile': p}
                    return render_to_response("edit.html", c,
                        context_instance=RequestContext(request))
            except:
                return HttpResponse(simplejson.dumps({'response': response,
                                                      'result': 'error'}))
    else:
        form = PersonForm(instance=p)  # An unbound form

    c = {'form': form, 'profile': p}
    return render_to_response("edit.html", c,
        context_instance=RequestContext(request))


class RequestListView(ListView):
    queryset = Request.objects.order_by('-priority', 'time')
    context_object_name = 'requests_list'
    template_name = 'requests.html'
    paginate_by = 10


def change_priority_view(request, pk, action):
    r = Request.objects.get(pk=pk)
    if action == 'inc':
        r.priority = r.priority + 1
    else:
        r.priority = r.priority - 1
    r.save()
    queryset = Request.objects.order_by('-priority', 'time')
    for index, item in enumerate(queryset):
        if r.pk == item.pk:
            break

    return redirect('/requests/{0}'.format((index / 10) + 1))

TestTask1/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    {% block js %}
        <script type="text/javascript">

        </script>
    {% endblock %}
    <title>
        mindmaster test task
    </title>
</head>
<body>

{% block content %} {% endblock %}
<hr>
{% block links %}
    <a href="/">home</a>
    <br>
    <a href="/requests/">requests</a>
{% endblock %}
</body>
</html>

TestTask1/templates/edit.html
{% extends "base.html" %}

{% block js %}

    <script type="text/javascript" src="/static/js/jquery.js"></script>
    <script type="text/javascript" src="/static/js/jquery.form.js"></script>
    {{ form.media }}
    <script type="text/javascript">
        function display_form_errors(errors, $form) {
            for (var k in errors) {
                $form.find('input[name=' + k + ']').after('<div class="error">' + errors[k] + '</div>');
            }
        }
        $(document).ready(function () {
            $('form').bind('submit', function () {
                //Prevent default form submit
                return false;
            });
            var myForm = $('form').find('input, textarea');
            $('#save').live('click', function () {
                $(myForm).prop('readonly', true);
                $('#save_form').ajaxSubmit({
                    beforeSubmit:function (arr, $form, options) {
                        $('#error').hide();
                        $('#success').hide();
                        $('#load').show("fast");

                    },
                    success:function (data, statusText, xhr, $form) {
                        $form.find('.error').remove();
                        if (data['result'] == 'success') {
                            $('#photo').attr('src', data['response']);
                            $('#success').show("slow");
                        }
                        else if (data['result'] == 'error') {
                            $('#error').show("fast");
                            display_form_errors(data['response'], $form);
                        }
                        $('#load').hide("fast");
                        $(myForm).prop('readonly', false);
                    },
                    error:function () {
                        alert("Failed to submit!");
                        $('#load').hide("fast");
                        $(myForm).prop('readonly', false);
                    },
                    timeout:10000,
                    dataType:'json'
                });
            });
        })
    </script>
    <style type="text/css">
        .yellow {
            background: yellow;
        }

        .red {
            background: red;
        }

        .green {
            background: #adff2f;
        }

        .error, .errorlist {
            color: red;
        }

        #load, #error, #success {
            display: none;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="load" class="yellow">
        Loading...
    </div>
    <div id="success" class="green">
        Success!
    </div>
    <div id="error" class="red">
        There are errors!
    </div>
    <form id="save_form" enctype="multipart/form-data" action="/edit/"
          method="post">{% csrf_token %}
        <table>
            <td width="300px" valign="top">
                {% for field in form %}

                    <div class="fieldWrapper">
                        {% if field.label == 'Photo' %}
                            <label for="id_photo">Photo:</label><br>
                            <img id="photo" width="150px"
                                 src="{{ profile.photo.url }}" alt=""><br>
                            Change: <input type="file" name="photo"
                                           id="id_photo"/>
                            {{ form.photo.errors }}
                        {% else %}
                            {{ field.label_tag }}: {{ field }}
                            {{ field.errors }}
                        {% endif %}
                    </div>
                    {% if forloop.counter == 4 %}
                        </td>
                        <td>
                    {% endif %}
                {% endfor %}
                </td>
        </table>
        <p><input id="save" type="submit" value="Save">
        <noscript>
            <input type="hidden" name="isJS" value="no">
        </noscript>
    </form>

{% endblock %}

TestTask1/templates/login.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}

    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}


    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="login"/>
        <input type="hidden" name="next" value="{{ next }}"/>
    </form>

{% endblock %}

TestTask1/templates/main_page.html
{% extends "base.html" %}

{% load my_tags %}


{% block content %}
    {% edit_link person %}<br>{% edit_link user %}
    {% if person %}
        <table>
            <tr>
                <td width="250px">
                    Name: {{ person.name }} <br>
                    Last name: {{ person.surname }} <br>
                    Birth date: {{ person.birth_date }} <br>
                    Photo: <br>

                </td>
                <td width="400px">
                    Skype: {{ person.skype }} <br>
                    e-mail: {{ person.email }} <br>
                    Phone: {{ person.phone }} <br>

                </td>
                <td valign="top">
                    {% if user.is_authenticated %}
                        <a href="/edit/">Edit</a>
                        <a href="/logout/">Logout</a>
                    {% else %}
                        <a href="/login/">Login</a>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>
                    <img width="150px" src="{{ person.photo.url }}" alt="">
                </td>
                <td valign="top">
                    Bio: <br>
                    {{ person.bio }}
                </td>
            </tr>
        </table>

    {% else %}
        <p>No available info.</p>
    {% endif %}

{% endblock %}

{% block links %}
    <a href="/requests/">requests</a>
{% endblock %}

TestTask1/templates/requests.html
{% extends "base.html" %}

{% block content %}
    <ul>
        {% for r in requests_list %}
            <li>{{ r.time }} - {{ r.header }}, <i>priority</i>: {{ r.priority }}
                (<a href="/request/{{ r.pk }}/inc">&uarr;&nbsp;</a>|<a href="/request/{{ r.pk }}/dec">&darr;&nbsp;</a>)
            </li>
        {% endfor %}
    </ul>
    {% if paginator.num_pages > 1 %}
        Pages:&nbsp;
        {% if page_obj.has_previous %}
            <a href="/requests/{{ page_obj.previous_page_number }}/">&larr;</a>
        {% endif %}
        {{ page_obj.number }}
        {% if page_obj.has_next %}
            <a href="/requests/{{ page_obj.next_page_number }}/">&rarr;</a>
        {% endif %}
    {% endif %}
{% endblock %}

{% block links %}
    <a href="/">home</a>
{% endblock %}